language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab7-tables
  - make -j
  - cd ./bin/
  - ./test_tables --gtest_list_tests
notifications:
  email: false
